apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-credentials

type: Opaque    # Opaque means from aks perspective, the contents of this secret is unstructured. It can contain arbitary key-value pairs
data:
  db-password: RmVsaWNpYTIzNCE=   #Run on terminal echo -n 'Felicia234!' | base64 and use the encrypted/encoded value of your passwd or go to https://www.base64encode.org

  db-username: bG9jYWxhZG1pbg==   # output of echo -n 'localadmin' | base64
  db-port: MzMwNg==               # output of echo -n '3306' | base64
