apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "checking database pod deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e ">> db started";' ]
      containers:
        - name: webb-app
          image: signaturedevops.azurecr.io/http      #you will have to use an app image that already has mysql installed and configured in it
          imagePullPolicy: Always                                 #Always. every time the kubelet launches a container,
                                                                 #the kubelet queries the container image registry to resolve the name to an image digest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOSTNAME
              value: "signaturemysqldb.mysql.database.azure.com"        #details comes from mysql clusterIP service manifest we already created/external name service for AzureMysql server usage
            - name: DB_PORT 
              value: "3306"
            - name: DB_NAME
              value: webapp
            - name: DB_USERNAME
              value: "your-username"
            - name: DB_PASSWORD
              value: "mypassword"

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-loadbalancer
  labels:
    app: web-app
spec:
  type: LoadBalancer
  selector: 
    app: web-app
  ports: 
    - port: 80
      targetPort: 8080    ##Container port
