apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  app.properties: |
    APP_ENV=production
    LOG_LEVEL=debug
  database.properties: |
    DB_HOST=mydb.example.com
    DB_PORT=5432




apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: configmap-demo
  template:
    metadata:
      labels:
        app: configmap-demo
    spec:
      containers:
        - name: demo-container
          image: busybox
          command: ["sleep", "3600"]                                 # Keeps the container running
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config                                  # Mounts ConfigMap as a directory
      volumes:
        - name: config-volume
          configMap:
            name: my-config                                           # Reference the ConfigMap created above

