apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx0-deployment
  labels:
    app: nginx0-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx0
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      containers:
      - name: nginx
        image: signaturedevops.azurecr.io/nginx-v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: signature-app-pod-loadbalancer-service      ##Name of service

spec:
  type: NodePort
  selector:
  # Loadbalance traffic across Pods matching this label selector
    app: signature-app
  ports:
    - name: http
      port: 80  #service port
      targetPort: 80    #Container Port

