apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "checking database pod deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e ">> db started";' ]
      containers:
        - name: webb-app
          image: signaturedevops.azurecr.io/http
          imagePullPolicy: Always                                 #Always. every time the kubelet launches a container,
                                                                 #the kubelet queries the container image registry to resolve the name to an image digest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOSTNAME
              value: "mysql"                #match external name service created earlier 
            - name: DB_PORT 
              value: "3306"
            - name: DB_NAME
              value: web-appdb      #db created after we logged into the mysql server we created on the portal (kubectl run --it --rm --image=mysql:8.0 etc)
            - name: DB_USERNAME
              value: "root"         # localadmin user created during the mysql server service we created during the creation on the portal)
            - name: DB_PASSWORD
              value: "chang3m3"     #Felicia234! the password we created for localadmin user

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-loadbalancer
  labels:
    app: web-app
spec:
  type: LoadBalancer
  selector: 
    app: web-app
  ports: 
    - port: 80
      targetPort: 8080    ##Container port
