apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: signaturemysqldb.mysql.database.azure.com      #From the azure portal mysql created get the server name
