apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec: 
  type: NodePort
  ports:
    - targetPort: vproapp-port  
      port: 8090        
      nodePort: 30000  
      protocol: TCP
  selector:
    app: vproapp


# You need the pod label for Nodeport(selector)  and port number to configure NodePort
