apiVersion: v1                                                                        #string
kind: Pod                                                                             #string
metadata:                                                                             #Dictionary
  name: signature-app
  labels:                                                                             #Dictionary
    role: frontendApp                                                                 #Key value pair
spec:
  replicas: 2
  selector:
    matchLabels:
      app: signature-app
spec:
  containers:                                                                          #List
    - name: signature-app
      image: signaturedevops.azurecr.io/http
      ports:                                                                           #List
        - name: web 
          containerPort: 80
          protocol: "TCP"

---
apiVersion: v1
kind: Service
metadata:
  name: signature-app-pod-loadbalancer-service      

spec: 
  type: LoadBalancer                                                                    # Type can be LoadBalancer, ClusterIp, NodePort
  selector: 
    app: signature-app                                                              # Loadbalancer traffic across Pods matching this label selector
  ports:
    - name: web
      port: 80                                                                           #service port
      targetPort: 80                                                                     #Container Port
